name: mishelle
analytics: {}
content_rating:
  adult: false
github: true
opengraph: {}
title: MuzeuMM and other adventures
author:
  name: mishelle moross
  email: digiartgal@gmail.com
color:
  lightness: 0.6774547513754701
  brandColors:
    - '#004358'
    - '#1F8A70'
    - '#BEDB39'
    - '#FFE11A'
    - '#FD7400'
  saturation: 0.2981399389212346
  brandStrength: 0.05304030539771549
  rhythmicContrast: 0.7372011748927648
